### ISSUE TITLE
Sending video

### ISSUE THREAD

**Issue by HypedMind** [smashah/sulla#11]
Hi guys, anyone of you tried sending a video?

This is my code:
```javascript
const fileBase64 = "data:video/mp4;base64,....";
 
await client.sendFile(
    to,
    fileBase64,
    "Video.mp4",
    "Video"
);
```

The message can be sent, but the message rendered as 'file' type instead of a 'video' message. 
![Image of Yaktocat](https://i.imgur.com/vtCiGZt.jpg)

**Comment by smashah** [comment]
@HypedMind I've now also seen this behaviour with video. It will take some investigating.

**Comment by paramirez** [comment]
sendMessageWithThumb

`
public async sendMessageWithThumb(thumb: string, url: string, title: string, description: string, chatId: string, done?: string) {
    return await this.page.evaluate(
      ({ thumb, url, title, description, chatId }) => {
        WAPI.sendSeen(chatId);
        WAPI.sendMessageWithThumb(thumb, url, title, description, chatId)
      },
      { thumb, url, title, description, chatId }
    );
  }
`

**Comment by HypedMind** [comment]
I did some finding on this, probably the web.whatsapp doesn't have the api available to send video as a 'video message', because using web.whatsapp in browser to send video also sends as a 'file message'.

**Comment by smashah** [comment]
@HypedMind this is not entirely the case because sending a video file (received through WhatsApp) on WhatsApp web, it works properly with the preview.

**Comment by HypedMind** [comment]
@smashah Yah the preview works fine. Probably WhatsApp decides that WhatsApp Web doesn’t need api to send video message, because only smartphone can capture video?

**Comment by smashah** [comment]
@HypedMind I've been sending some videos to my other number on whatsapp web. Preview only didnt work for one specific video (that was received and saved by sulla-hotfix sample a few days ago).

**Comment by smashah** [comment]
Just a thought: This may be due to user agent. My previous two comments were when testing on chrome whatsapp web. I tried with {headless:false} and i got this error message while sending a video with the chromium instance from puppeteer 

![image](https://user-images.githubusercontent.com/5903821/69495024-4236d700-0ed3-11ea-85f9-efcb53f64d2c.png)

**Comment by smashah** [comment]
Further Investigation:

![image](https://user-images.githubusercontent.com/5903821/69495477-7b257a80-0ed8-11ea-89ac-cda8daf918a8.png)

**Comment by smashah** [comment]
Related: 
https://github.com/alfred82santa/whalesong/issues/58

**Comment by smashah** [comment]
Ok, I've got it working properly with the demo/index.ts

Because pupeteer does not have any codecs that means that it cannot process videos for whatsapp. Why is this just happening now? I'm guessing that because Whatsapp doesn't want to be dealing with all the videos coming through, it now requires some pre processing on the client (phone or web). 

There's two ways to solve this.

1. Fool whatsapp web into thinking it's been processed with puppeteer.
2. Use an instance of chrome instead of chromium for puppeteer.

I have no clue right now to do number 1. But 2 works fine, all you need to do is tell sulla-hotfix where your chrome instance is. Here is the solution for my mac. If you're running this on a server, make sure chrome is installed.

```
create('session',{
  executablePath: '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',
}).then(client => start(client));
```

The good thing about this is that it will not require an update. However I have been testing with puppeteer dependency to latest version (don't think it should make much diff though).

@HypedMind @paramirez Let me know if this works for you.

I will update the documentation soon. It's kinda annoying but it's definitely a long term solution.

Thanks for bringing up the issue and helping with investigation!

**Comment by HypedMind** [comment]
Hey @smashah , sorry now only I have the time to check.

I just tried with your solution, however I can't get it to work, the message rendered as a 'file' message instead of a 'video' message.

Would you able to share the video file that you use?

My sulla.create:
```
var client = await sulla.create(session_id,
            {
                executablePath: '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',
            },
            customUserAgent = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.97 Safari/537.36"
        );
```

My sendFile code:
```
await client.sendFile(
                {number},
                base64,
                "",
                ""
            );
```

My video file: [http://s000.tinyupload.com/index.php?file_id=53242422432601226909](url)

My base64 string: [https://freetexthost.net/kHHzVgU](url)

My chrome version: [https://i.imgur.com/hbBwEVX.png](img)

**Comment by smashah** [comment]
@HypedMind classic buck bunny. That file doesnt work for some reason. If you use the sample and send your sulla'd number a video it should work fine. Maybe it's because of the codec? Does this specific file work in whatsapp web itself? It doesn't work in my instance of whatsapp web desktop client or the in chrome.

**Comment by HypedMind** [comment]
@smashah Turns out the video I used actually has issue. I got it working with other video files.

I was able to send out video as 'video message' in Ubuntu server.

This was how I did it:

1. Install Chrome in Ubuntu following this tutorial: [https://www.linuxbabe.com/ubuntu/install-google-chrome-ubuntu-16-04-lts](url)

2. Create sulla client using the executable path:
```
var client = await sulla.create(session_id,
            {
                executablePath: "/opt/google/chrome/chrome",
            }
        )
```
