### ISSUE TITLE
Detect if the main device is online

### ISSUE THREAD

**Issue by HypedMind** [smashah/sulla#14]
I have a use case where I need some alert when the main device is offline.

The method I found is `WAPI.isConnected`, essentially detecting the 'Phone not connected' banner in the UI.

However it doesn't work as in the method doesn't return `false` when the main device is offline.

The command `document.querySelector('*[data-icon="alert-phone"]')` is working in web.whatsapp browser.

Anyone have ideas?

**Comment by smashah** [comment]
@HypedMind I've tested it out.

```WAPI.isConnected()```

is as reliable as and changed state at the same moment as:

```document.querySelector('*[data-icon="alert-phone"]') ? 'offline' : 'online'```

With my testing I would turn off the data on my phone and then test it out in whatsapp web. I would have to force an offline detection by sending a message via whatsapp web, otherwise it just remains as 'online' untill it checks again. I'm not entirely certain how often those checks occur.

So if ```WAPI.isConnected()``` isn't good enough in terms of real time accuracy, then there needs to be another solution.

**Comment by smashah** [comment]
@HypedMind You can use client.isConnected() now in v1.2.10

**Comment by phantom-limb** [comment]
@smashah, Can you provide an example usage? Tks!

**Comment by smashah** [comment]
@phantom-limb https://github.com/smashah/sulla/blob/e41abd3203b47e50bc1f0223ec191cfdac391f86/demo/index.ts#L17
