### ISSUE TITLE
When restart the server it does not use the session

### ISSUE THREAD

**Issue by tatosjb** [smashah/sulla#45]
I have tried with the headless mode off and this is what i see:

![image](https://user-images.githubusercontent.com/7603203/72351582-620e9e00-36bf-11ea-9ed4-5ec9fa094340.png)

![image](https://user-images.githubusercontent.com/7603203/72351541-4e633780-36bf-11ea-9b97-3a3f16371a66.png)

**Comment by smashah** [comment]
This is just a fact of life with this project. I suggest switching up the user agent once in a while.


```javascript


//1st argument is the session name
//2nd argument is the puppeteer config override
//3rd argument is the user agent override

create('session',
{
  headless: false
},
'some custom user agent HERE')
.then(client => start(client));

```



For reference this is the default user agent:
https://github.com/smashah/sulla/blob/473789c06e0428064d17da3d37880a653ae901b0/src/config/puppeteer.config.ts#L44

**Comment by fernandolcardoso** [comment]
The same happens to me, I changed the agent to "**Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.117 Safari/537.36**", deleted the session folder, restarted and the same error is reproduced.

Any tips for resolving the session issue?

**Comment by smashah** [comment]
@fernandolcardoso it's not a resolvable issue. It will keep coming back. I suggest reading this issue to learn more on how to try to prevent.

https://github.com/smashah/sulla/issues/9

**Comment by smashah** [comment]
Check out this comment https://github.com/smashah/sulla/issues/9#issuecomment-553144416

**Comment by dogcalas** [comment]
There is not received message by sulla when the error comes up. I am monitoring on my phone all received message, and I notice the failure because the bot is not responding on an user message. From the last sent message by the bot to the error time there is a difference of 5 hours. The message without response came 8 hours later. 

I need that if it fails, at least close the process to restart the container.

**Comment by smashah** [comment]
Next line of attack is to bypass/reverse engineer the checking code if possible.

**Comment by smashah** [comment]
Just as a reference. The reason this is happening is because the websocket state is being tagged with TOS_BLOCK flag. Resulting in this error.

**Comment by smashah** [comment]
@tatosjb @fernandolcardoso I've updated the default user agent in v 1.5.0 This will require a whole lot of work in order to cleanse your websockets of the TOS_BLOCK flag. Can I ask if your implementations have a lot of users in production or are only in dev for now. This may shed some light on your specific situations.

**Comment by fernandolcardoso** [comment]
Hi @smashah, I am currently using only one account and for testing purposes.

**Comment by fernandolcardoso** [comment]
@smashah I would like to inform you that I have performed session restart tests and so far is working correctly.

**Comment by smashah** [comment]
That's great @fernandolcardoso . This will happen from time to time, especially now with the rollout of new edge browser, looks like Facebook is updating a lot of code. The best practice is to:

1. Keep the session alive
2. Offload most work off of your sulla-hotfix setup (i.e forward all events to a pubsub or something)
3. Keep the phone nearby just in case you need to reauthenticate
4. Use a chrome instance instead of the default chromium instance
5. Use ```headless: false``` for easy & quick visual debugging
6. Implement the unread messages functionality on creation of a session so you don't miss any messages upon any downtime.

**Comment by tatosjb** [comment]
I started to use chrome and it solved the issue. I think its not a problem to use chrome instead of chrome. 

What you mean by "unread messages". To save the messeges in a database and resync every time I connect?

**Comment by smashah** [comment]
@tatosjb https://github.com/smashah/sulla/issues/22#issuecomment-569605974

**Comment by tatosjb** [comment]
I this is solved, so i will close the issue, thanks.
