### ISSUE TITLE
The sendText method is not sending seen

### ISSUE THREAD

**Issue by mrbarnk** [smashah/sulla#95]
The blue marker on whatsapp that identifies that the message has been read is no longer working.

Please help look into that,

**Comment by smashah** [comment]
@mrbarnk I've tried this manually it seems to be working fine. I cannot help you if you don't use the bug template or at least provide all the detail that is required in the template:
https://github.com/smashah/sulla/issues/new?assignees=&labels=&template=bug_report.md&title=

I really want to help out but I also have other things to do which is why I want people to use the template so we can be as efficient as possible here.
